version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.10.11
    - 3.10.12
    - 3.10.2
    - 3.10.3
    - 3.10.6
    - 3.10.7
    - 3.10.9
    - 3.13.0
    - 3.13.1
    - 3.13.10
    - 3.13.3
    - 3.13.7
    - 3.13.8
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.16.0
    - 3.17.1
    - 3.17.2
    - 3.18.0
    - 3.21.12
    - 3.21.2
    - 3.21.6
    - 3.4.3
    - 3.4.5
    - 3.5.0
    - 3.7.1
    - 3.8.0
    - 3.8.3
    - 3.8.4
    - 3.8.6
  - dependency-name: antd
    versions:
    - 4.10.3
    - 4.12.0
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
  - dependency-name: ethers
    versions:
    - 5.0.26
    - 5.0.27
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
  - dependency-name: web3
    versions:
    - 1.3.3
    - 1.3.4
  - dependency-name: "@types/numeral"
    versions:
    - 2.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jest
    versions:
    - 26.2.2
