version: 2.1

parameters:
  # By default we enable the main workflow
  trigger:
    type: boolean
    default: true

  # Add a boolean parameter on each package.
  contracts:
    type: boolean
    default: false
  app:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run:
          name: Trigger workflows
          command: node ./circleci.js
  lint:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - run:
          name: Running linter on << parameters.package_name >>
          command: echo << parameters.package_name >> lint

  test:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - run:
          name: Running test on << parameters.package_name >>
          command: echo << parameters.package_name >> test

workflows:
  version: 2

  # The main workflow will trigger other workflow based on your changes
  trigger:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.
  contracts:
    when: << pipeline.parameters.contracts >>
    jobs:
      - lint:
          package_name: contracts

  app:
    when: << pipeline.parameters.app >>
    jobs:
      - test:
          package_name: app
      #- lint:
      #    package_name: app
