version: 2.1

orbs:
  node: circleci/node@0.0.9

jobs:
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/fyght

    steps:
      - checkout

      # Install root dependencies
      - restore_cache:
          key: dependency-cache-v1-root-{{ checksum "package.json" }}
      - run:
          name: Install root dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-v1-root-{{ checksum "package.json" }}
          paths: ["./node_modules"]

      # Run tests
      - run:
          name: Lint
          command: npm run lint

      # Run tests
      - run:
          name: Test
          command: npm test
